- name: Install packages
  ansible.builtin.apt:
    pkg:
      - tcpdump
      - pigz
      - python3-pandas

- name: Install python module nfstream
  ansible.builtin.pip:
    name: nfstream
    extra_args: --break-system-packages

- name: Create pcap directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit)}}"
  with_items:
    - {"path":"{{ data_dir }}/pcap/", "owner":tcpdump, "group":tcpdump }
    - {"path":"{{ data_dir }}/pcap_done/"}
    - {"path":"{{ data_dir }}/csv/"}
    - {"path":"{{ data_dir }}/csv_done/"}
    - {"path":"{{ data_dir }}/csv_merged/"}

- name: Genarate config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { "src": packet-capture.conf.j2, "dest": /etc/packet-capture.conf }

- name: Copy packet scripts
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - {"src":packet-capture.sh, "dest":/usr/local/sbin/packet-capture.sh}
    - {"src":pcap_rotate.sh, "dest":/usr/local/bin/pcap_rotate.sh}
    - {"src":pcap2csv.py, "dest":/usr/local/bin/pcap2csv.py}
    - {"src":pcap2csv.sh, "dest":/usr/local/bin/pcap2csv.sh}
    - {"src":merge_csv.py, "dest":/usr/local/bin/merge_csv.py}
    - {"src":merge_csv.sh, "dest":/usr/local/bin/merge_csv.sh}
    - {"src":pcap2csv.cron, "dest":/usr/local/bin/pcap2csv.cron}

- name: Add PATH
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

- name: Create cron entry 1
  ansible.builtin.cron:
    name: "start packet capture"
    minute: 0
    hour: 8
    weekday: 1-5
    user: root
    job: "packet-capture.sh -i {{ capture_if }} -r {{ capture_rotates | default('1') }} -s {{ capture_seconds | default('28800') }} > /var/log/packet-capture.log 2>&1"
  when: capture_if is defined

- name: Delete cron entry 1
  ansible.builtin.cron:
    name: "start packet capture"
    state: absent
  when: capture_if is not defined

- name: Create cron entry 2
  ansible.builtin.cron:
    name: "analyze capture data"
    minute: 0
    hour: 23
    weekday: 1-5
    user: root
    job: "pcap2csv.cron > /var/log/pcap2csv.log 2>&1"
  when: capture_if is defined

- name: Delete cron entry 2
  ansible.builtin.cron:
    name: "analyze capture data"
    state: absent
  when: capture_if is not defined