- name: copy scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - { "src":hotswap_enable.sh, "dest":/usr/local/bin/ }
    - { "src":update_boot.sh, "dest":/usr/local/bin/ }
    - { "src":micon_scripts/libmicon.py, "dest":/usr/local/bin/micon_scripts/ }
    - { "src":micon_scripts/micon_shutdown.py, "dest":/usr/local/bin/micon_scripts/ }
    - { "src":micon_scripts/micon_startup.py, "dest":/usr/local/bin/micon_scripts/ }

- name: copy hotswap.service
  copy:
    src: hotswap.service
    dest: /etc/systemd/system/

- name: copy micon_boot.service
  copy:
    src: micon_scripts/micon_boot.service
    dest: /etc/systemd/system/

- name: create /etc/initramfs-tools/post-update.d/
  file:
    path: /etc/initramfs-tools/post-update.d/
    state: directory
    recurse: yes

- name: create link to update_boot
  file:
    src: /usr/local/bin/update_boot.sh
    dest: /etc/initramfs-tools/post-update.d/update_boot
    state: link

- name: create link to micon_shutdown
  file:
    src: /usr/local/bin/micon_scripts/micon_shutdown.py
    dest: /lib/systemd/system-shutdown/micon_shutdown
    state: link

- name: enable hotswap.service
  systemd:
    name: hotswap.service
    daemon-reload: yes
    state: started
    enabled: yes

- name: enable micon_boot.service
  systemd:
    name: micon_boot.service
    state: started
    enabled: yes