- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify:
    update-lcd

- name: edit /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: '127.0.1.1 {{ hostname.split(".")[0] }} {{ hostname }}'
