- name: Install fluent-bit
  ansible.builtin.shell: curl https://raw.githubusercontent.com/fluent/fluent-bit/master/install.sh | sudo sh

- name: Create nginx dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit)}}"
  with_items:
    - {"path":"{{ data_dir }}/nginx/log2/"}


- name: Generate config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { "src": fluent-bit.conf.j2, "dest": /etc/fluent-bit/fluent-bit.conf }
    - { "src": parsers.conf.j2, "dest": /etc/fluent-bit/parsers.conf }
  notify: Reload fluent-bit
