#!/bin/bash
LED_TARGET=$1
LED_MODE=$2
MICONAPL='/usr/local/sbin/miconapl'

for i in {1..10}; do
    ${MICONAPL} -a mcon_get_version
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 1
done

CURRENT_ON=`${MICONAPL} -a led_set_on_off | sed -r -e's/#.*//g' -e's/led_.*=off//g' -e 's/led_(.*)=on/\1/g' | sed -rz -e's/\s+/ /g'`
CURRENT_BLINK=`${MICONAPL} -a led_set_blink | sed -r -e's/#.*//g' -e's/led_.*=off//g' -e 's/led_(.*)=on/\1/g' | sed -rz -e's/\s+/ /g'`

case ${LED_MODE} in
on)
    NEW_ON="${CURRENT_ON} ${LED_TARGET}"
    NEW_BLINK=`echo ${CURRENT_BLINK} | sed "s/\b${LED_TARGET}\b//"`
    ;;
off)
    NEW_ON=`echo ${CURRENT_ON} | sed "s/\b${LED_TARGET}\b//"`
    NEW_BLINK=`echo ${CURRENT_BLINK} | sed "s/\b${LED_TARGET}\b//"`
    ;;
blink)
    NEW_ON="${CURRENT_ON} ${LED_TARGET}"
    NEW_BLINK="${CURRENT_BLINK} ${LED_TARGET}"
    ;;
*)
    echo "Invalid mode: ${LED_MODE}" 2>&1
    exit 1
esac
NEW_ON=`echo "${NEW_ON}" | sed -rz -e's/\s+/ /g' -e's/^\s+//' -e's/\s+$//'`
NEW_BLINK=`echo "${NEW_BLINK}" | sed -rz -e's/\s+/ /g' -e's/^\s+//' -e's/\s+$//'`
if [ -z "${NEW_ON}" ]; then
    NEW_ON='off'
fi
if [ -z "${NEW_BLINK}" ]; then
    NEW_BLINK='off'
fi

echo "NEW_ON=${NEW_ON}"
echo "NEW_BLINK=${NEW_BLINK}"

${MICONAPL} -a led_set_on_off ${NEW_ON}
${MICONAPL} -a led_set_blink ${NEW_BLINK}
