#!/bin/sh
MICONAPL='/usr/local/sbin/miconapl'

for i in {1..10}; do
    ${MICONAPL} -a mcon_get_version
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 1
done

${MICONAPL} -a lcd_set_dispitem hostname date buffer6 buffer7
${MICONAPL} -a lcd_changemode_auto
${MICONAPL} -a lcd_set_hostname "`hostname`"
${MICONAPL} -a lcd_set_buffer6 "IP $(ip a show dev br0 | grep 'inet ' | awk '{print $2}' | head -n 1)"
