- name: install required packages
  apt:
    name:
      - curl
      - gnupg2

- name: check zerotier-one exists
  command: dpkg -l zerotier-one
  register: zerotier_exists
  check_mode: no
  changed_when: no
  failed_when: no

- name: install zerotier
  shell:
    cmd: curl -s https://install.zerotier.com | bash
    warn: no
  when: zerotier_exists.rc != 0

- name: join network
  command: zerotier-cli join {{ zerotier_network_id }}
  when: zerotier_exists.rc != 0