#!/bin/sh
MICONAPL='/usr/local/sbin/miconapl'

for i in {1..10}; do
    ${MICONAPL} -a mcon_get_version
    if [ $? -eq 0 ]; then
        break
    fi
    sleep 1
done

${MICONAPL} -a lcd_set_dispitem hostname date buffer6 buffer7
${MICONAPL} -a lcd_changemode_auto
${MICONAPL} -a lcd_set_hostname "`hostname`"
${MICONAPL} -a lcd_set_buffer6 "BRIDGE LAN1/LAN2`ifconfig br-inline | grep 'netmask' | awk '{print $2}'`"
${MICONAPL} -a lcd_set_buffer7 "REV-PROXY   LAN3`ifconfig br-reverse | grep 'netmask' | awk '{print $2}'`"
