#!/bin/bash
REVERSE_ANSWER_A_TEMPLATE='/etc/coredns/reverse.answer.a.conf.template'
REVERSE_ANSWER_A_CONF='/etc/coredns/reverse.answer.a.conf'
REVERSE_ANSWER_AAAA_TEMPLATE='/etc/coredns/reverse.answer.aaaa.conf.template'
REVERSE_ANSWER_AAAA_CONF='/etc/coredns/reverse.answer.aaaa.conf'
INLINE_ANSWER_A_TEMPLATE='/etc/coredns/inline.answer.a.conf.template'
INLINE_ANSWER_A_CONF='/etc/coredns/inline.answer.a.conf'
INLINE_ANSWER_AAAA_TEMPLATE='/etc/coredns/inline.answer.aaaa.conf.template'
INLINE_ANSWER_AAAA_CONF='/etc/coredns/inline.answer.aaaa.conf'

REVERSE_IP4=`ifconfig br-reverse | grep 'netmask' | awk '{print $2}'`
REVERSE_IP6=`ifconfig br-reverse | grep '<global>' | awk '{print $2}'`
INLINE_IP4=`ifconfig br-inline | grep 'netmask' | awk '{print $2}'`
INLINE_IP6=`ifconfig br-inline | grep '<global>' | awk '{print $2}'`

([ -n "${REVERSE_IP4}" ] && sed "s/<IP>/${REVERSE_IP4}/g" ${REVERSE_ANSWER_A_TEMPLATE}) > ${REVERSE_ANSWER_A_CONF}
([ -n "${REVERSE_IP6}" ] && sed "s/<IP>/${REVERSE_IP6}/g" ${REVERSE_ANSWER_AAAA_TEMPLATE}) > ${REVERSE_ANSWER_AAAA_CONF}
([ -n "${INLINE_IP4}" ] && sed "s/<IP>/${INLINE_IP4}/g" ${INLINE_ANSWER_A_TEMPLATE}) > ${INLINE_ANSWER_A_CONF}
([ -n "${INLINE_IP6}" ] && sed "s/<IP>/${INLINE_IP6}/g" ${INLINE_ANSWER_AAAA_TEMPLATE}) > ${INLINE_ANSWER_AAAA_CONF}

systemctl reload coredns
