network:
  inline:
    dhcp4: true
  reverse:
    dhcp4: false
    address4: "192.168.11.253"
    gateway4: "192.168.11.1"
    nameservers:
      - "192.168.11.1"
    friend-servers: []
proxy-cache:
  enable: false
  targets:
    dl-google-com:
      domains:
        - dl.google.com
      preset: dl-google-com
      schemes:
        - http
        - https
      locations:
        - path: /
          cache:
            enable: true
            valid: 23h
            ignore-cache-control: true
    edumalldemo:
      domains:
        - edumalldemo.es.edumall.jp
      preset: edumall
      schemes:
        - https
      locations:
        - path: /
          cache:
            enable: false
        - path: /edge/EduMallContents/
          cache:
            enable: true
            valid: 23h
            ignore-cache-control: true
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
    kyoiku-shuppan:
      domains:
        - www.kyoiku-shuppan.co.jp
      preset: kyoiku-shuppan
      schemes:
        - https
      proxy-ssl-ciphers:
        - "!DH"
      locations:
        - path: /
          cache:
            enable: false
        - path: "~ ^/.*/digital/"
          cache:
            enable: true
            valid: 23h
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
    lentrance:
      domains:
        - www.lentrance.com
      preset: lentrance
      schemes:
        - https
      locations:
        - path: /
          cache:
            enable: false
        - path: /contents/
          cache:
            enable: true
            valid: 23h
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
        - path: /reader/
          cache:
            enable: true
            valid: 23h
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
    manaviewer:
      domains:
        - manaviewer.jp
      preset: manaviewer
      schemes:
        - https
      locations:
        - path: /
          cache:
            enable: false
        - path: /textbook/manaviewer-textbooks/inddb/
          cache:
            enable: true
            valid: 23h
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
    mirai-pf:
      domains:
        - mirai-pf.jp
      preset: mirai-pf
      schemes:
        - https
      locations:
        - path: /
          cache:
            enable: true
            valid: 23h
            extensions:
              - css
              - gif
              - ico
              - jpeg
              - jpg
              - js
              - mp3
              - png
              - svg
              - ttf
